spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/smart%20remainder}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.web.cors.allowed-origin-patterns=http://localhost:*,http://127.0.0.1:*,https://*.vercel.app

gemini.api.key=${GEMINI_API_KEY:dummy_key}

ai.service.url=${AI_SERVICE_URL:http://localhost:8000}

firebase.config.base64=${FIREBASE_CONFIG_BASE64:dummy_config}

app.frontend.url=${APP_FRONTEND_URL:http://localhost:5173}

server.port=${PORT:8080}

spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID:dummy_id}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET:dummy_secret}
spring.security.oauth2.client.registration.google.scope=email,profile
spring.security.oauth2.client.registration.google.redirect-uri=${GOOGLE_REDIRECT_URI:http://localhost:8080/login/oauth2/code/google}